repos:
  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: "^(.*/migrations/|testproject/testproject/settings/)"
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: "^.tx/"
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: "^(.tx/.*|.*\\.map)$"
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    -   id: reorder-python-imports
