version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  tox:
    parameters:
      tox_env:
        description: "Name of Tox environment to run"
        default: "py38"
        type: string
      python_version:
        description: "Python version string"
        default: "3.8"
        type: string
    description: "Reusable job for invoking tox"
    docker:
    - image: circleci/python:<<parameters.python_version>>
    steps:
      - checkout
      - run:
          command: |
            pip install tox
      - run:
          command: |
            tox -e <<parameters.tox_env>>
          name: Test

workflows:
  main:
    jobs:
      - tox:
          tox_env: "py38"
          python_version: "3.8"
      - tox:
          tox_env: "py310"
          python_version: "3.10"
